# Generated by Django 5.1.6 on 2025-03-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_products_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name_plural": "Brands"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categorys"},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="rating",
            new_name="ratings",
        ),
        migrations.AlterField(
            model_name="category",
            name="imageUrl",
            field=models.URLField(blank=True),
        ),
    ]
